### ISSUE TITLE
Cannot build with haskell-src-exts>=1.17.0&&<1.18

### ISSUE THREAD

**Issue by bezirg** [bmillwood/haskell-src-meta#68]
I think the dependencies are too relaxed in the `.cabal` file.
They should be more strict by requiring `haskell-src-exts>=1.18`.

When building: `cabal install haskell-src-exts-1.17.0 haskell-src-meta-0.8.0.1` , I get a built error.

```
src\Language\Haskell\Meta\Syntax\Translate.hs:357:17: error:
    Not in scope: data constructor `Hs.LazyTy'
    Neither `Language.Haskell.Exts.Annotated.Syntax' nor `Language.Haskell.Exts.SrcLoc' exports `LazyTy'.
    |
357 |       toStrict (Hs.LazyTy _) = SourceLazy
    |                 ^^^^^^^^^

src\Language\Haskell\Meta\Syntax\Translate.hs:359:17: error:
    Not in scope: data constructor `Hs.NoStrictAnnot'
    Neither `Language.Haskell.Exts.Annotated.Syntax' nor `Language.Haskell.Exts.SrcLoc' exports `NoStrictAnnot'.
    |
359 |       toStrict (Hs.NoStrictAnnot _) = NoSourceStrictness
    |                 ^^^^^^^^^^^^^^^^

src\Language\Haskell\Meta\Syntax\Translate.hs:360:17: error:
    Not in scope: data constructor `Hs.Unpack'
    Neither `Language.Haskell.Exts.Annotated.Syntax' nor `Language.Haskell.Exts.SrcLoc' exports `Unpack'.
    |
360 |       toUnpack (Hs.Unpack _) = SourceUnpack
    |                 ^^^^^^^^^

src\Language\Haskell\Meta\Syntax\Translate.hs:361:17: error:
    Not in scope: data constructor `Hs.NoUnpack'
    Neither `Language.Haskell.Exts.Annotated.Syntax' nor `Language.Haskell.Exts.SrcLoc' exports `NoUnpack'.
    |
361 |       toUnpack (Hs.NoUnpack _) = SourceNoUnpack
    |                 ^^^^^^^^^^^

src\Language\Haskell\Meta\Syntax\Translate.hs:362:17: error:
    Not in scope: data constructor `Hs.NoUnpackPragma'
    Neither `Language.Haskell.Exts.Annotated.Syntax' nor `Language.Haskell.Exts.SrcLoc' exports `NoUnpackPragma'.
    |
362 |       toUnpack (Hs.NoUnpackPragma _) = NoSourceUnpackedness
    |                 ^^^^^^^^^^^^^^^^^

src\Language\Haskell\Meta\Syntax\Translate.hs:542:28: error:
    Not in scope: type constructor or class `Hs.InjectivityInfo'
    Neither `Language.Haskell.Exts.Annotated.Syntax' nor `Language.Haskell.Exts.SrcLoc' exports `InjectivityInfo'.
    |
542 | instance ToInjectivityAnn (Hs.InjectivityInfo l) where
    |                            ^^^^^^^^^^^^^^^^^^

src\Language\Haskell\Meta\Syntax\Translate.hs:543:21: error:
    Not in scope: data constructor `Hs.InjectivityInfo'
    Neither `Language.Haskell.Exts.Annotated.Syntax' nor `Language.Haskell.Exts.SrcLoc' exports `InjectivityInfo'.
    |
543 |   toInjectivityAnn (Hs.InjectivityInfo _ n ns) = InjectivityAnn (toName n) (fmap toName ns)
    |                     ^^^^^^^^^^^^^^^^^^
cabal: Leaving directory 'C:\Users\Nikolaos\AppData\Local\Temp\cabal-tmp-692\haskell-src-meta-0.8.0.1'
cabal: Error: some packages failed to install:
haskell-src-meta-0.8.0.1-2Zf0uJmOHHZKv7Cn7xleYK failed during the building
phase. The exception was:
ExitFailure 1
```

**Comment by mainland** [comment]
Should be fixed now, thanks!
